services:
  customers:
    image: customers-image
    ports:
      - 5000:5000
    expose:
      - 5000:5000
    build:
      dockerfile: ./customers_service/Dockerfile
    working_dir: /app
    volumes:
      - ./customers_service:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: sekret
      MYSQL_DB: car_rental_db
      APP_HOST: customers:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    volumes:
      - car-rental-mysql-data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:rw
    environment:
      MYSQL_ROOT_PASSWORD: sekret
      MYSQL_DATABASE: car_rental_db
    ports:
      - 3306:3306
    expose:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  car-rental-mysql-data:
