services:
  app:
    image: python:3.11.4-alpine3.18
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: sekret
      MYSQL_DB: car_rental_db

  db:
    image: mysql:8
    volumes:
      - car-rental-mysql-data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:rw
    environment:
      MYSQL_ROOT_PASSWORD: sekret
      MYSQL_DATABASE: car_rental_db
    ports:
      - 3306:3306
    expose:
      - 3306:3306

volumes:
  car-rental-mysql-data:
