name:  e2e testing

on:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run docker-compose
      run: docker compose -f docker-compose.yml up -d
    - name: 'Test'
      run: docker compose exec customers make test-e2e
