name:  CI

on:
  push

defaults:
  run:
    working-directory: ./customers_service
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --no-deps --upgrade pip
            pip install pipenv
        - name: Lint with pylint
          run: |
            pipenv install --dev
            make check
        - name: Test with pytest
          run: |
            pipenv install --dev
            make test-unit
            make test-integration
